# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  FQarch_config = debug

else ifeq ($(config),release)
  FQarch_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := FQarch

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

FQarch:
ifneq (,$(FQarch_config))
	@echo "==== Building FQarch ($(FQarch_config)) ===="
	@${MAKE} --no-print-directory -C . -f FQarch.make config=$(FQarch_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f FQarch.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   FQarch"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"